require File.expand_path(File.join(File.dirname(__FILE__), 'feed', 'element_support'))
require File.expand_path(File.join(File.dirname(__FILE__), 'feed', 'author'))
require File.expand_path(File.join(File.dirname(__FILE__), 'feed', 'category'))
require File.expand_path(File.join(File.dirname(__FILE__), 'feed', 'entry'))
require File.expand_path(File.join(File.dirname(__FILE__), 'feed', 'page'))
require File.expand_path(File.join(File.dirname(__FILE__), 'feed', 'changes'))
